name: CI - Tests backend

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-backend:
    name: ğŸ” Tests Java avec Maven
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: ğŸ“¥ Checkout du code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: ğŸ“¦ Cache des dÃ©pendances Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: ğŸš€ Build + Tests
        run: mvn clean verify

      - name: ğŸ“Š GÃ©nÃ©rer le rapport de couverture JaCoCo
        run: mvn jacoco:report

  test-frontend:
    name: Tests Angular + Coverage
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸš€ Run Angular tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: ğŸ“¤ Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage-report
          path: front/coverage

  analyse-sonar:
    name: ğŸ“Š Analyse SonarCloud
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    defaults:
      run:
        working-directory: back

    steps:
      - name: ğŸ“¥ Checkout du code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: ğŸ“¦ Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-sonar

      - name: ğŸ” Analyse SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORG }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}